# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderUp', '0003_auto_20171019_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=160)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('resturant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OrderUp.Resturant')),
            ],
        ),
    ]
